name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_PACKAGES_TOKEN_VARIABLE: ${{ secrets.GH_PACKAGES_TOKEN_VARIABLE }}

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Buildx setup
      uses: docker/setup-buildx-action@v2
      
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: fib_image:latest
        
    - name: Build the image
      run: |
        docker build -t fib_image:v1 -platform=linux/amd64,linux/arm64 .
    - name: sdfs
      run: |
        docker images
        
    - name: Log into the GitHub Packages Container Registry (ghcr)
      run: |
        echo $GITHUB_PACKAGES_TOKEN_VARIABLE | docker login ghcr.io -u simonsssssss --password-stdin
