name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Buildit setup
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
