name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_PACKAGES_TOKEN_VARIABLE: ${{ secrets.GH_PACKAGES_TOKEN_VARIABLE }}

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Buildit setup
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        id: fib_image
        
    - name: Log into the GitHub Packages Container Registry (ghcr)
      run: |
        echo $GITHUB_PACKAGES_TOKEN_VARIABLE | docker login ghcr.io -u simonsssssss --password-stdin
    - name: Tag the image to make it available for the push to ghcr.io
      run: |
        docker tag fib_image ghcr.io/simonsssssss/fibonacci_sequence:v1
