name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        engine: buildkit
        architectures: intel64,arm64
        push: false
        tags: fibcalc:latest
        image-name: fibcalc
