name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_PACKAGES_TOKEN_VARIABLE: ${{ secrets.GH_PACKAGES_TOKEN_VARIABLE }}

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Buildx setup
      uses: docker/setup-buildx-action@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Log into the DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        
    - name: Log into the GitHub Packages Container Registry (ghcr)
      run: |
        echo $GITHUB_PACKAGES_TOKEN_VARIABLE | docker login ghcr.io -u simonsssssss --password-stdin
      
   # - name: Build the Docker image
    #  uses: docker/build-push-action@v3
     # with:
      #  context: .
       # file: ./Dockerfile
        #platforms: linux/amd64,linux/arm64
        #push: true
        #tags: fib_image:latest
        
    - name: sdfsrdtrd
      run: |
        docker images
